name: Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # weekly

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install pip-tools
          pip-compile requirements.in
          pip-compile requirements-dev.in
      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git diff --exit-code || (git commit -am "chore: bump dependencies" && git push)
